# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Indranil Guha
title: Graduate Research Assistant
email: indranil-guha@uiowa.edu
website: https://github.com/iguha94


# Social links
#researchgate_username: Indranil_Guha3
googlescholar_username: dAWFL-wAAAAJ
github_username:  iguha94
linkedin_username: indranil-guha-07603895
# About Section
# about_title: About Me
about_profile_image: images/profileMe.jpeg
about_content: | # this will include new lines to allow paragraphs
  My name is Indranil and I am currently a third year PhD student at the Department of Electrical and Computer Engineering at the University of Iowa. I am working with prof. Punam Kumar Saha, in Advanced Pulmonary Physiomic Imaging Laboratory (APPIL). I earned my bachelors degree in computer science and engineering from Jadavpur University in 2016. After Completing my bachelors, I worked as software development engineer at Time Inc India (Now Meredith Corporation) for one year before joining UIOWA in fall 2017.

  My research work is primarily focused on the development of statistical methods for quantitative imaging, musculoskeletal and pulmonary imaging, and high resolution CT-image reconstruction. 
  

# Projects Section
projects_title: Publications

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
