# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Indranil Guha
title: PhD Candidate, ECE Department, University of Iowa
email: indranil-guha@uiowa.edu
address: C721, General Hospital(GH), Iowa City, IA, 52246, USA

# Social links
#researchgate_username: Indranil_Guha3
googlescholar_username: dAWFL-wAAAAJ
github_username:  iguha94
linkedin_username: indranil-guha-07603895
# About Section
# about_title: About Me
about_profile_image: images/profileMe.jpeg
about_content: | # this will include new lines to allow paragraphs
  I am currently a third year PhD student at the Department of Electrical and Computer Engineering at the University of Iowa. I am pursuing my PhD under the guidence of prof. Punam Kumar Saha, in Advanced Pulmonary Physiomic Imaging Laboratory (APPIL). I earned my bachelors degree in computer science and engineering from Jadavpur University in 2016. After Completing my bachelors, I worked as software development engineer at Time Inc India (Now Meredith Corporation) for one year before joining UIOWA in fall 2017.

  My current research interests are in the development of <b>statistical methods for quantitative imaging</b> and <b> morphometric analysis of human bone and lung structures</b>. I am  also interested in developing <b>deep learning</b> models for high resolution <b>CT-image reconstruction</b> and <b>pulmonary artery-vein segmentation</b>. 
  

# Projects Section
projects_title: Publications

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

# More Section
more_title: Conference Talks
more_content: | # this will include new lines to allow paragraphs
  <b>February 2020 -</b> I will present the paper titled "Deep learning-based high-resolution reconstruction of trabecular bone microstructures from low-resolution CT scans using GAN-CIRCLE" at SPIE Medical Imaging conference in Houston, Texas.

  <b>February 2018 -</b> Presented the paper titled "Segmentation and assessment of structural plasticity of hippocampal dendritic spines from 3D confocal light microscopy" at SPIE Medical Imaging conference in Houston, Texas.<a href="/images/SPIE_PRESENTATION_final.pptx" target="_blank">(ppt)</a>

more_title: Awards and Honors
more_content: | # this will include new lines to allow paragraphs
  <b>2016:</b>  ACM-Kolkata chapter-ICACNI 2016 Best Paper Award in advanced computing category.
  
  <b>2017:</b>  Time Inc innovation award 2017 for my work in document classification.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
