# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Indranil Guha
title: Graduate Research Assistant
email: indranil-guha@uiowa.edu
website: https://github.com/iguha94

# Social links
scholar_userid: dAWFL-wAAAAJ
github_username:  iguha94
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: indranil-guha-07603895
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profileMe.jpeg
about_content: | # this will include new lines to allow paragraphs
Hi, My name is Indranil and currently a third year PhD student at the Department of Electrical and Computer Engineering at University of Iowa. I am working with prof. Punam Kumar Saha, in Advanced Pulmonary Physiomic Imaging Laboratory (APPIL). I earned my bachelors degree in computer science and engineering from Jadavpur University in 2016. After Completing my bachelors, I worked as software development engineer at Time Inc India (Now Meredith Corporation) for one year before joining UIOWA in August 2017.

I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
